version: '3.1'
name: notification-relay 
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: example_password 
      POSTGRES_DB: notifications

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080