version: '3.1'
name: rust_authentication
services:
  db:
    container_name:  rust_auth_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: example_password 
      POSTGRES_DB: accounts

  adminer:
    container_name: rust_auth_adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
        
  redis:
    container_name: rust_auth_redis
    image: redis
    restart: always
    ports:
      - 6379:6379
