name: Build

on:
  push:
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --release --features postgres
      - run: cargo build --release --features redis
      - run: cargo build --release
  